# Generated by Django 3.2 on 2021-09-02 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('candidate_contact', models.CharField(max_length=10)),
                ('candidate_mail', models.EmailField(max_length=254)),
                ('candidate_cv', models.FileField(upload_to='media/')),
                ('avialable_for', models.CharField(choices=[('In Office', 'In Office'), ('Work From Home', 'Work From Home')], max_length=30)),
                ('company', models.CharField(max_length=50)),
                ('technology', models.CharField(max_length=50)),
                ('post', models.CharField(max_length=30)),
                ('scheduled_date', models.DateField()),
                ('scheduled_time', models.TimeField()),
                ('scheduled_by', models.CharField(max_length=100)),
                ('interviewr_name', models.CharField(max_length=100)),
                ('interviewr_mail', models.EmailField(max_length=254)),
                ('status', models.CharField(max_length=50)),
                ('remark', models.CharField(choices=[('Showed Up', 'Showed Up'), ('Showed Not', 'Showed Not')], max_length=30)),
            ],
        ),
    ]
