# Generated by Django 3.2 on 2021-09-10 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_alter_candidate_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='candidate_cv',
        ),
        migrations.AlterField(
            model_name='candidate',
            name='avialable_for',
            field=models.CharField(choices=[('In Office', 'In Office'), ('Work From Home', 'Work From Home')], max_length=80),
        ),
    ]
