# Generated by Django 3.2 on 2021-09-27 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_candidate_candidate_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='remark',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='status',
            field=models.CharField(blank=True, choices=[('Showed Up', 'Showed Up'), ('Showed Not', 'Showed Not')], max_length=30),
        ),
    ]
