# Generated by Django 3.2 on 2021-09-30 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_auto_20210927_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='company',
            field=models.CharField(choices=[('Uptricks', 'Uptricks'), ('Kukbit', 'Kukbit'), ('Skillbit', 'Skillbit'), ('Learntricks', 'Learntricks'), ('Challengekatta', 'Challengekatta'), ('Happieloop', 'Happieloop'), ('Internshipmela', 'Internshipmela')], max_length=50),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='post',
            field=models.CharField(choices=[('Internship', 'Internship'), ('Job', 'Job')], max_length=50),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='technology',
            field=models.CharField(choices=[('Video Editor Animation', 'Video Editor Animation'), ('Android Development', 'Android Development'), ('Game Development', 'Game Development'), ('Graphics Designing', 'Graphics Designing'), ('Software Testing', 'Software Testing'), ('Manual Testing', 'Manual Testing'), ('Full-stack Development', 'Full-stack Development'), ('Human Resource', 'Human Resource'), ('Digital Marketing', 'Digital Marketing'), ('Wordpress Development', 'Wordpress Development'), ('Web Auditor', 'Web Auditor'), ('Web developer', 'Web developer'), ('Business development executive', 'Business development executive'), ('Machine learning', 'Machine learning'), ('Machine learning', 'Machine learning'), ('AWS', 'AWS')], max_length=50),
        ),
    ]
